### ISSUE TITLE
Crash report: `TypeError: Cannot convert undefined or null to object`

### ISSUE THREAD

**Issue by TokenSale1** [Horizon-Dex/issues-report#27]
## URL

https://app.horizondex.io/swap

## Error

```
TypeError: Cannot convert undefined or null to object
```

## Stacktrace

```
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at https://app.horizondex.io/static/js/main.2923b483.chunk.js:2:5108906
    at Object.Zo [as useMemo] (https://app.horizondex.io/static/js/main.2923b483.chunk.js:2:2817864)
    at t.useMemo (https://app.horizondex.io/static/js/main.2923b483.chunk.js:2:3028903)
    at w (https://app.horizondex.io/static/js/main.2923b483.chunk.js:2:5108865)
    at O (https://app.horizondex.io/static/js/main.2923b483.chunk.js:2:5109204)
    at S (https://app.horizondex.io/static/js/main.2923b483.chunk.js:2:5110876)
    at I (https://app.horizondex.io/static/js/main.2923b483.chunk.js:2:5111859)
    at https://app.horizondex.io/static/js/main.2923b483.chunk.js:2:6228343
    at M (https://app.horizondex.io/static/js/main.2923b483.chunk.js:2:6230022)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/116.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "116.0.0.0",
    "major": "116"
  },
  "engine": {
    "name": "Blink",
    "version": "116.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by TokenSale1** [comment]
will not connect coinbase wallet to site. keeps connecting metamask wallet
