### ISSUE TITLE
Crash report: `TypeError: Cannot read properties of undefined (reading 'toString')`

### ISSUE THREAD

**Issue by aawadat** [Horizon-Dex/issues-report#3]
## URL

https://app.horizondex.io/swap

## Error

```
TypeError: Cannot read properties of undefined (reading 'toString')
```

## Stacktrace

```
TypeError: Cannot read properties of undefined (reading 'toString')
    at https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5449543
    at Array.reduce (<anonymous>)
    at https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5449071
    at Object.Zo [as useMemo] (https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:2796732)
    at t.useMemo (https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:3010595)
    at https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5448801
    at vb (https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5449945)
    at https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5451745
    at xb (https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5452776)
    at Oo (https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:2792321)
```

## Device data

```json
{
  "ua": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36",
  "browser": {
    "name": "Chrome",
    "version": "115.0.0.0",
    "major": "115"
  },
  "engine": {
    "name": "Blink",
    "version": "115.0.0.0"
  },
  "os": {
    "name": "Windows",
    "version": "10"
  },
  "device": {},
  "cpu": {
    "architecture": "amd64"
  }
}
```

**Comment by aawadat** [comment]
Oops! Something went wrong
TypeError: Cannot read properties of undefined (reading 'toString')
    at https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5449543
    at Array.reduce (<anonymous>)
    at https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5449071
    at Object.Zo [as useMemo] (https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:2796732)
    at t.useMemo (https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:3010595)
    at https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5448801
    at vb (https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5449945)
    at https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5451745
    at xb (https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:5452776)
    at Oo (https://app.horizondex.io/static/js/main.fd6f4921.chunk.js:2:2792321)
[Create an issue on GitHub↗](https://github.com/Horizon-Dex/issues-report/issues/new?assignees=&labels=bug&body=%23%23%20URL%0A%0Ahttps%3A%2F%2Fapp.horizondex.io%2Fswap%0A%0A%23%23%20Error%0A%0A%60%60%60%0ATypeError%3A%20Cannot%20read%20properties%20of%20undefined%20(reading%20%27toString%27)%0A%60%60%60%0A%0A%23%23%20Stacktrace%0A%0A%60%60%60%0ATypeError%3A%20Cannot%20read%20properties%20of%20undefined%20(reading%20%27toString%27)%0A%20%20%20%20at%20https%3A%2F%2Fapp.horizondex.io%2Fstatic%2Fjs%2Fmain.fd6f4921.chunk.js%3A2%3A5449543%0A%20%20%20%20at%20Array.reduce%20(%3Canonymous%3E)%0A%20%20%20%20at%20https%3A%2F%2Fapp.horizondex.io%2Fstatic%2Fjs%2Fmain.fd6f4921.chunk.js%3A2%3A5449071%0A%20%20%20%20at%20Object.Zo%20%5Bas%20useMemo%5D%20(https%3A%2F%2Fapp.horizondex.io%2Fstatic%2Fjs%2Fmain.fd6f4921.chunk.js%3A2%3A2796732)%0A%20%20%20%20at%20t.useMemo%20(https%3A%2F%2Fapp.horizondex.io%2Fstatic%2Fjs%2Fmain.fd6f4921.chunk.js%3A2%3A3010595)%0A%20%20%20%20at%20https%3A%2F%2Fapp.horizondex.io%2Fstatic%2Fjs%2Fmain.fd6f4921.chunk.js%3A2%3A5448801%0A%20%20%20%20at%20vb%20(https%3A%2F%2Fapp.horizondex.io%2Fstatic%2Fjs%2Fmain.fd6f4921.chunk.js%3A2%3A5449945)%0A%20%20%20%20at%20https%3A%2F%2Fapp.horizondex.io%2Fstatic%2Fjs%2Fmain.fd6f4921.chunk.js%3A2%3A5451745%0A%20%20%20%20at%20xb%20(https%3A%2F%2Fapp.horizondex.io%2Fstatic%2Fjs%2Fmain.fd6f4921.chunk.js%3A2%3A5452776)%0A%20%20%20%20at%20Oo%20(https%3A%2F%2Fapp.horizondex.io%2Fstatic%2Fjs%2Fmain.fd6f4921.chunk.js%3A2%3A2792321)%0A%60%60%60%0A%0A%23%23%20Device%20data%0A%0A%60%60%60json%0A%7B%0A%20%20%22ua%22%3A%20%22Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F115.0.0.0%20Safari%2F537.36%22%2C%0A%20%20%22browser%22%3A%20%7B%0A%20%20%20%20%22name%22%3A%20%22Chrome%22%2C%0A%20%20%20%20%22version%22%3A%20%22115.0.0.0%22%2C%0A%20%20%20%20%22major%22%3A%20%22115%22%0A%20%20%7D%2C%0A%20%20%22engine%22%3A%20%7B%0A%20%20%20%20%22name%22%3A%20%22Blink%22%2C%0A%20%20%20%20%22version%22%3A%20%22115.0.0.0%22%0A%20%20%7D%2C%0A%20%20%22os%22%3A%20%7B%0A%20%20%20%20%22name%22%3A%20%22Windows%22%2C%0A%20%20%20%20%22version%22%3A%20%2210%22%0A%20%20%7D%2C%0A%20%20%22device%22%3A%20%7B%7D%2C%0A%20%20%22cpu%22%3A%20%7B%0A%20%20%20%20%22architecture%22%3A%20%22amd64%22%0A%20%20%7D%0A%7D%0A%60%60%60%0A%0A&title=Crash%20report%3A%20%60TypeError%3A%20Cannot%20read%20properties%20of%20undefined%20(reading%20%27toString%27)%60)
